/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourtextpageRouteImport } from './routes/yourtextpage'
import { Route as IndexRouteImport } from './routes/index'

const YourtextpageRoute = YourtextpageRouteImport.update({
  id: '/yourtextpage',
  path: '/yourtextpage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yourtextpage': typeof YourtextpageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yourtextpage': typeof YourtextpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yourtextpage': typeof YourtextpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yourtextpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yourtextpage'
  id: '__root__' | '/' | '/yourtextpage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YourtextpageRoute: typeof YourtextpageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yourtextpage': {
      id: '/yourtextpage'
      path: '/yourtextpage'
      fullPath: '/yourtextpage'
      preLoaderRoute: typeof YourtextpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YourtextpageRoute: YourtextpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
